### ISSUE TITLE
Erreur checkout "Veuillez choisir une carte."

### ISSUE THREAD

**Issue by thedotwriter** [E-Transactions-CA/etransactions23#6]
Bonjour,

Dans le checkout, lors du choix de la méthode de paiement, quand on sélectionne la méthode `etep_cb`, cette erreur est lancé par la requête ajax `rest/fr/V1/carts/mine/set-payment-information` (car le champ `cc_type` n'est pas envoyé lors de la sélection du mode de paiement): 
```
{"message":"Veuillez choisir une carte.","trace":"#0 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(88): CreditAgricole\\Etransactions\\Observer\\DataAssignObserver->execute()
#1 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/Event\/Invoker\/InvokerDefault.php(74): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod()
#2 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/module-staging\/Model\/Event\/Manager.php(97): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch()
#3 \/home\/synbshop\/public_html\/project\/src\/generated\/code\/Magento\/Staging\/Model\/Event\/Manager\/Proxy.php(95): Magento\\Staging\\Model\\Event\\Manager->dispatch()
#4 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/module-payment\/Model\/Method\/AbstractMethod.php(825): Magento\\Staging\\Model\\Event\\Manager\\Proxy->dispatch()
#5 \/home\/synbshop\/public_html\/project\/src\/vendor\/creditagricole\/etransactions\/Model\/Payment\/AbstractPayment.php(264): Magento\\Payment\\Model\\Method\\AbstractMethod->assignData()
#6 \/home\/synbshop\/public_html\/project\/src\/generated\/code\/CreditAgricole\/Etransactions\/Model\/Payment\/Cb\/Interceptor.php(50): CreditAgricole\\Etransactions\\Model\\Payment\\AbstractPayment->assignData()
#7 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/module-quote\/Model\/Quote\/Payment.php(197): CreditAgricole\\Etransactions\\Model\\Payment\\Cb\\Interceptor->assignData()
#8 \/home\/synbshop\/public_html\/project\/src\/generated\/code\/Magento\/Quote\/Model\/Quote\/Payment\/Interceptor.php(41): Magento\\Quote\\Model\\Quote\\Payment->importData()
#9 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/module-quote\/Model\/PaymentMethodManagement.php(79): Magento\\Quote\\Model\\Quote\\Payment\\Interceptor->importData()
#10 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Quote\\Model\\PaymentMethodManagement->set()
#11 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Quote\\Model\\PaymentMethodManagement\\Interceptor->___callParent()
#12 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Quote\\Model\\PaymentMethodManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}()
#13 \/home\/synbshop\/public_html\/project\/src\/generated\/code\/Magento\/Quote\/Model\/PaymentMethodManagement\/Interceptor.php(23): Magento\\Quote\\Model\\PaymentMethodManagement\\Interceptor->___callPlugins()
#14 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/module-checkout\/Model\/PaymentInformationManagement.php(178): Magento\\Quote\\Model\\PaymentMethodManagement\\Interceptor->set()
#15 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Checkout\\Model\\PaymentInformationManagement->savePaymentInformation()
#16 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->___callParent()
#17 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}()
#18 \/home\/synbshop\/public_html\/project\/src\/generated\/code\/Magento\/Checkout\/Model\/PaymentInformationManagement\/Interceptor.php(32): Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->___callPlugins()
#19 [internal function]: Magento\\Checkout\\Model\\PaymentInformationManagement\\Interceptor->savePaymentInformation()
#20 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/module-webapi\/Controller\/Rest\/SynchronousRequestProcessor.php(95): call_user_func_array()
#21 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/module-webapi\/Controller\/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process()
#22 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch()
#23 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent()
#24 \/home\/synbshop\/public_html\/project\/src\/vendor\/fastly\/magento2\/Model\/FrontControllerPlugin.php(131): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}()
#25 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Fastly\\Cdn\\Model\\FrontControllerPlugin->aroundDispatch()
#26 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/module-company\/Plugin\/Webapi\/Controller\/RestPlugin.php(84): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}()
#27 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Magento\\Company\\Plugin\\Webapi\\Controller\\RestPlugin->aroundDispatch()
#28 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}()
#29 \/home\/synbshop\/public_html\/project\/src\/generated\/code\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(23): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins()
#30 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/App\/Http.php(116): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch()
#31 \/home\/synbshop\/public_html\/project\/src\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(23): Magento\\Framework\\App\\Http->launch()
#32 \/home\/synbshop\/public_html\/project\/src\/vendor\/magento\/framework\/App\/Bootstrap.php(263): Magento\\Framework\\App\\Http\\Interceptor->launch()
#33 \/home\/synbshop\/public_html\/project\/src\/pub\/index.php(29): Magento\\Framework\\App\\Bootstrap->run()
#34 {main}"}
```

Cela ne bloque pas le processus de paiement mais cela ne va pas rassurer le client de voir une erreur lors d'un workflow normal. Cela peux impacter le business de la boutique.

Pouvez-vous corriger ça rapidement ?

**Comment by thedotwriter** [comment]
Bonjour,

Pouvez-vous nous donner une update sur ce point ?

Merci d'avance

**Comment by thedotwriter** [comment]
Bonjour,

Pouvez-vous nous donner une update sur ce point ?

Merci d'avance

**Comment by Tibo16** [comment]
Bonjour, 
Exactement le même problème ici...
Une piste, un travail en cours ?

Merci !

**Comment by thedotwriter** [comment]
Bonjour,

Possible d'avoir un retour sur ce ticket ?

**Comment by Tibo16** [comment]
Bonjour 

Je n’ai pas accès à ce ticket…. 

Bien à vous
Thibaut simonin
Webiliz
